# Generated by Django 4.2.2 on 2023-06-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='site_version',
            field=models.CharField(default='v1.0.0-beta1', max_length=50),
        ),
    ]
