# Generated by Django 4.2.2 on 2023-06-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_generalsettings_site_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalsettings',
            name='site_url',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/', null=True),
        ),
    ]
