# Generated by Django 4.2.2 on 2023-06-24 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0003_alter_generalsettings_site_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='generalsettings',
            options={'verbose_name': 'Genel Ayarlar', 'verbose_name_plural': 'Genel Ayarlar'},
        ),
        migrations.AlterModelOptions(
            name='linkssettings',
            options={'verbose_name': 'Bağlantı Ayarları', 'verbose_name_plural': 'Bağlantı Ayarları'},
        ),
        migrations.AlterModelTable(
            name='generalsettings',
            table='general_settings',
        ),
        migrations.AlterModelTable(
            name='linkssettings',
            table='links_settings',
        ),
    ]
