# Generated by Django 4.2.2 on 2023-06-26 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0004_alter_generalsettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalsettings',
            name='site_privacy_policy',
            field=models.TextField(null=True, verbose_name='Gizlilik Politikası'),
        ),
        migrations.AddField(
            model_name='generalsettings',
            name='site_terms_of_use',
            field=models.TextField(null=True, verbose_name='Kullanım Şartları'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='site_author',
            field=models.CharField(blank=True, default='acunmedyaakademi', max_length=255, null=True, verbose_name='Meta Author Metni'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='site_copyright',
            field=models.CharField(blank=True, default='AcunMedyaAkademi', max_length=255, null=True, verbose_name='Copyright Metni'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='site_description',
            field=models.CharField(blank=True, default='AcunmedyaAkademi Videolar', max_length=255, null=True, verbose_name='Meta Açıklama'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='site_developers',
            field=models.CharField(blank=True, default='Furkan Özay', max_length=255, null=True, verbose_name='Geliştiriciler'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='site_keywords',
            field=models.CharField(blank=True, default='akademi,acunmedyaakademi,acunmedyaakademi videolar', max_length=255, null=True, verbose_name='Meta Anahtar Kelimeler'),
        ),
        migrations.AlterField(
            model_name='generalsettings',
            name='site_version',
            field=models.CharField(default='v1.0.0-beta1', max_length=50, verbose_name='Versiyon'),
        ),
    ]
