# Generated by Django 4.2.2 on 2023-07-02 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('subject', models.CharField(max_length=150, verbose_name='Konu')),
                ('content', models.TextField(verbose_name='İçerik')),
                ('completed_on', models.DateTimeField(blank=True, null=True, verbose_name='Tamamlanma Tarihi')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Görevli')),
            ],
            options={
                'verbose_name': 'Destek Talebi',
                'verbose_name_plural': 'Destek Talepleri',
                'db_table': 'tickets',
            },
        ),
        migrations.CreateModel(
            name='TicketCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(max_length=150, verbose_name='Kategori Adı')),
                ('color', models.CharField(choices=[('red', 'Kırmızı'), ('blue', 'Mavi'), ('green', 'Yeşil'), ('orange', 'Turuncu'), ('gray', 'Gri')], default='red', max_length=20, verbose_name='Kategori Renk')),
            ],
            options={
                'verbose_name': 'Destek Talebi Kategorisi',
                'verbose_name_plural': 'Destek Talebi Kategorileri',
                'db_table': 'ticket_categories',
            },
        ),
        migrations.CreateModel(
            name='TicketPriorities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(max_length=150, verbose_name='Öncelik Adı')),
                ('color', models.CharField(choices=[('red', 'Kırmızı'), ('blue', 'Mavi'), ('green', 'Yeşil'), ('orange', 'Turuncu'), ('gray', 'Gri')], default='blue', max_length=20, verbose_name='Öncelik Renk')),
            ],
            options={
                'verbose_name': 'Destek Talebi Önceliği',
                'verbose_name_plural': 'Destek Talebi Öncelikleri',
                'db_table': 'ticket_priorities',
            },
        ),
        migrations.CreateModel(
            name='TicketStatuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(max_length=150, verbose_name='Durum Adı')),
                ('color', models.CharField(choices=[('red', 'Kırmızı'), ('blue', 'Mavi'), ('green', 'Yeşil'), ('orange', 'Turuncu'), ('gray', 'Gri')], default='green', max_length=20, verbose_name='Durum Renk')),
            ],
            options={
                'verbose_name': 'Destek Talebi Durumu',
                'verbose_name_plural': 'Destek Talebi Durumları',
                'db_table': 'ticket_statuses',
            },
        ),
        migrations.CreateModel(
            name='TicketMessages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('content', models.TextField()),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='ticket.ticket', verbose_name='Destek Talebi')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_comments', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı')),
            ],
            options={
                'verbose_name': 'Destek Talebi Mesajı',
                'verbose_name_plural': 'Destek Talebi Mesajları',
                'db_table': 'ticket_messages',
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='category_tickets', to='ticket.ticketcategories', verbose_name='Kategori'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='priority_tickets', to='ticket.ticketpriorities', verbose_name='Öncelik'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='status_tickets', to='ticket.ticketstatuses', verbose_name='Durum'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Kullanıcı'),
        ),
    ]
