# Generated by Django 4.2.2 on 2023-06-23 14:18

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('student_number', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Öğrenci Numarası')),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='Kullanıcı Adı')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='Eposta Adresi')),
                ('first_name', models.CharField(max_length=120, verbose_name='Adı')),
                ('last_name', models.CharField(max_length=120, verbose_name='Soyadı')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Profil Resmi')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Biyografi')),
                ('birth_date', models.DateField(null=True, verbose_name='Doğum Tarihi')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True, verbose_name='Ülke')),
                ('is_active', models.BooleanField(default=False, verbose_name='Aktif mi?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Personel mi?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Üye',
                'verbose_name_plural': 'Üyeler',
                'db_table': 'users',
            },
        ),
    ]
