# Generated by Django 4.2.2 on 2023-06-23 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_users_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_url', models.URLField(blank=True, default='127.0.0.1:8000/', null=True)),
                ('site_description', models.CharField(blank=True, default='AcunmedyaAkademi Videolar', max_length=255, null=True)),
                ('site_keywords', models.CharField(blank=True, default='akademi,acunmedyaakademi,acunmedyaakademi videolar', max_length=255, null=True)),
                ('site_author', models.CharField(blank=True, default='acunmedyaakademi', max_length=255, null=True)),
                ('site_copyright', models.CharField(blank=True, default='AcunMedyaAkademi', max_length=255, null=True)),
                ('site_developers', models.CharField(blank=True, default='Furkan Özay', max_length=255, null=True)),
            ],
        ),
    ]
