# Generated by Django 4.2.2 on 2023-06-23 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_users_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneralSettings',
        ),
        migrations.DeleteModel(
            name='LinksSettings',
        ),
    ]
