# Generated by Django 4.2.2 on 2023-06-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_issuecategories_alter_users_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issues',
            name='is_solved',
            field=models.BooleanField(default=False, verbose_name='Çözüldü mü?'),
        ),
    ]
