# Generated by Django 4.2.2 on 2023-06-23 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_issues_is_solved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('title', models.CharField(max_length=120, verbose_name='Başlık')),
                ('description', models.TextField(verbose_name='Açıklama')),
                ('video_file', models.FileField(upload_to='videos/', verbose_name='Video')),
                ('link', models.URLField(blank=True, null=True, verbose_name='Link')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
