# Generated by Django 4.2.2 on 2023-06-23 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_videos_instructor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issuecategories',
            options={'verbose_name': 'Sorun Kategorisi', 'verbose_name_plural': 'Sorun Kategorileri'},
        ),
        migrations.AlterModelOptions(
            name='issues',
            options={'verbose_name': 'Sorun', 'verbose_name_plural': 'Sorunlar'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name': 'Video', 'verbose_name_plural': 'Videolar'},
        ),
        migrations.AlterModelTable(
            name='issuecategories',
            table='issue_categories',
        ),
        migrations.AlterModelTable(
            name='issues',
            table='issues',
        ),
        migrations.AlterModelTable(
            name='videos',
            table='videos',
        ),
    ]
