# Generated by Django 4.2.2 on 2023-06-23 18:40

import apps.core.validators.videos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_issuecategories_options_alter_issues_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_file',
            field=models.FileField(upload_to='videos/', validators=[apps.core.validators.videos.validate_file_extension], verbose_name='Video'),
        ),
    ]
