# Generated by Django 4.2.2 on 2023-06-23 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_courses_classroom'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classroom',
            options={'verbose_name': 'Sınıf', 'verbose_name_plural': 'Sınıflar'},
        ),
        migrations.AlterModelOptions(
            name='courses',
            options={'verbose_name': 'Kurs', 'verbose_name_plural': 'Kurslar'},
        ),
        migrations.AddField(
            model_name='classroom',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Eğitmen'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classrooms', to='core.courses', verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=120, verbose_name='İsim'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='name',
            field=models.CharField(max_length=120, verbose_name='İsim'),
        ),
        migrations.AlterModelTable(
            name='classroom',
            table='classrooms',
        ),
        migrations.AlterModelTable(
            name='courses',
            table='courses',
        ),
    ]
