# Generated by Django 4.2.2 on 2023-06-23 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_classroom_options_alter_courses_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videos',
            name='instructor',
        ),
        migrations.AddField(
            model_name='videos',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.classroom'),
        ),
    ]
