# Generated by Django 4.2.2 on 2023-06-23 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_videos_instructor_videos_classroom'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('comment', models.TextField(verbose_name='Yorum')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_comments', to=settings.AUTH_USER_MODEL, verbose_name='Yazan')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='core.videos', verbose_name='Video')),
            ],
            options={
                'verbose_name': 'Video Yorumu',
                'verbose_name_plural': 'Video Yorumları',
                'db_table': 'video_comments',
            },
        ),
    ]
