# Generated by Django 4.2.2 on 2023-06-24 06:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_videocomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_videos', to=settings.AUTH_USER_MODEL),
        ),
    ]
