# Generated by Django 4.2.2 on 2023-06-25 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_classroom_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='classroom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.classroom', verbose_name='Sınıf'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_videos', to=settings.AUTH_USER_MODEL, verbose_name='Eğitmen'),
        ),
    ]
