# Generated by Django 4.2.2 on 2023-06-26 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_videos_classroom_alter_videos_instructor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('name', models.CharField(max_length=120, verbose_name='İsim')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='courses',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coursecategories', verbose_name='Kurs Kategorisi'),
        ),
    ]
