# Generated by Django 4.2.2 on 2023-06-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_coursecategories_courses_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursecategories',
            options={'verbose_name': 'Kurs Kategorisi', 'verbose_name_plural': 'Kurs Kategorileri'},
        ),
        migrations.AlterModelTable(
            name='coursecategories',
            table='course_categories',
        ),
    ]
