# Generated by Django 4.2.2 on 2023-06-26 07:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_coursecategories_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='instructor',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Eğitmen'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_classrooms', to=settings.AUTH_USER_MODEL, verbose_name='Eğitmen'),
        ),
    ]
