# Generated by Django 4.2.2 on 2023-06-27 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_classroom_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password',
        ),
    ]
