# Generated by Django 4.2.2 on 2023-06-27 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_videos_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issues',
            name='category',
        ),
        migrations.DeleteModel(
            name='IssueCategories',
        ),
        migrations.DeleteModel(
            name='Issues',
        ),
    ]
