# Generated by Django 4.2.2 on 2023-07-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_videofavorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='force_password_change',
            field=models.BooleanField(default=True, verbose_name='Şifre Değiştirme Gerekliliği'),
        ),
    ]
