# Generated by Django 4.2.2 on 2023-07-02 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_period_classroom_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_on', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('facebook', models.CharField(blank=True, max_length=120, null=True, verbose_name='Facebook')),
                ('twitter', models.CharField(blank=True, max_length=120, null=True, verbose_name='Twitter')),
                ('instagram', models.CharField(blank=True, max_length=120, null=True, verbose_name='Instagram')),
                ('github', models.CharField(blank=True, max_length=120, null=True, verbose_name='Github')),
                ('linkedin', models.CharField(blank=True, max_length=120, null=True, verbose_name='Linkedin')),
                ('youtube', models.CharField(blank=True, max_length=120, null=True, verbose_name='Youtube')),
                ('website', models.CharField(blank=True, max_length=120, null=True, verbose_name='Website')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to=settings.AUTH_USER_MODEL, verbose_name='Üye')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
