# Generated by Django 4.2.2 on 2023-07-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_remove_usersociallinks_facebook_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersociallinks',
            name='user',
        ),
        migrations.AddField(
            model_name='usersociallinks',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Başlık'),
        ),
    ]
