# Generated by Django 4.2.2 on 2023-07-02 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_usersociallinks_user_usersociallinks_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersociallinks',
            options={'verbose_name': 'Sosyal Link', 'verbose_name_plural': 'Sosyal Linkler'},
        ),
        migrations.AlterModelTable(
            name='usersociallinks',
            table='social_links',
        ),
    ]
