# Generated by Django 4.2.2 on 2023-07-02 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_alter_usersociallinks_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='social_links',
        ),
        migrations.AddField(
            model_name='usersociallinks',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Üye'),
            preserve_default=False,
        ),
    ]
