# Generated by Django 4.2.3 on 2023-07-21 08:55

import apps.core.validators.videos
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_alter_usersociallinks_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='video_url',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Video URL'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='videos/', validators=[apps.core.validators.videos.validate_file_extension], verbose_name='Video Dosyası'),
        ),
    ]
