# Generated by Django 4.2.3 on 2023-08-04 06:17

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_videos_video_url_alter_videos_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
        migrations.AlterField(
            model_name='users',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True, verbose_name='Ülke'),
        ),
        migrations.DeleteModel(
            name='UserSocialLinks',
        ),
    ]
