# Generated by Django 4.2.3 on 2023-08-04 06:38

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_alter_users_birth_date_alter_users_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='videos',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='title', unique=True),
        ),
    ]
