# Generated by Django 4.2.3 on 2023-08-04 06:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_videos_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='description',
            field=ckeditor.fields.RichTextField(null=True, verbose_name='Açıklama'),
        ),
    ]
